In [1]:
import pandas as pd

print(pd.__version__)

0.25.3

In [2]:
df = pd.read_csv('../data/raw_data.csv', index_col=0)
df.head()

,id,name,age,height,weight,preferred_foot,overall_rating,potential,team,best_overall,...,skill_moves,attacking_work_rate,defensive_work_rate,international_reputation,PAC,SHO,PAS,DRI,DEF,PHY
0,239053,F. Valverde,20,"6'0""",172lbs,Right,81,89,Real Madrid,82,...,3,High,High,1,76,73,77,77,73,79
1,225591,L. Suárez,23,"5'6""",132lbs,Left,71,79,Villarreal CF,73,...,4,Medium,Low,1,65,68,73,76,23,35
2,238160,M. Demiral,21,"6'4""",187lbs,Right,74,85,Juventus,75,...,2,Medium,High,1,68,39,48,57,75,75
3,236499,Douglas Luiz,21,"5'10""",154lbs,Right,74,87,Aston Villa,74,...,3,High,Medium,1,67,67,72,74,69,70
4,212198,Bruno Fernandes,24,"5'10""",152lbs,Right,85,88,Sporting CP,86,...,4,High,High,2,77,83,87,85,66,74

## height
First, we convert the height to inches.

In [21]:
df['height'] = list(map(lambda s: int(s.split('\'')[0])*12 + int(s.split('\'')[1].split('"')[0]), df['height']))

In [24]:
df.head()

,id,name,age,height,weight,preferred_foot,overall_rating,potential,team,best_overall,...,skill_moves,attacking_work_rate,defensive_work_rate,international_reputation,PAC,SHO,PAS,DRI,DEF,PHY
0,239053,F. Valverde,20,72,172lbs,Right,81,89,Real Madrid,82,...,3,High,High,1,76,73,77,77,73,79
1,225591,L. Suárez,23,66,132lbs,Left,71,79,Villarreal CF,73,...,4,Medium,Low,1,65,68,73,76,23,35
2,238160,M. Demiral,21,76,187lbs,Right,74,85,Juventus,75,...,2,Medium,High,1,68,39,48,57,75,75
3,236499,Douglas Luiz,21,70,154lbs,Right,74,87,Aston Villa,74,...,3,High,Medium,1,67,67,72,74,69,70
4,212198,Bruno Fernandes,24,70,152lbs,Right,85,88,Sporting CP,86,...,4,High,High,2,77,83,87,85,66,74

## weight

We remove the `lbs` suffix from weight.

In [25]:
df['weight'] = list(map(lambda x: x.split('lbs')[0], df['weight']))

In [26]:
df.head()

,id,name,age,height,weight,preferred_foot,overall_rating,potential,team,best_overall,...,skill_moves,attacking_work_rate,defensive_work_rate,international_reputation,PAC,SHO,PAS,DRI,DEF,PHY
0,239053,F. Valverde,20,72,172,Right,81,89,Real Madrid,82,...,3,High,High,1,76,73,77,77,73,79
1,225591,L. Suárez,23,66,132,Left,71,79,Villarreal CF,73,...,4,Medium,Low,1,65,68,73,76,23,35
2,238160,M. Demiral,21,76,187,Right,74,85,Juventus,75,...,2,Medium,High,1,68,39,48,57,75,75
3,236499,Douglas Luiz,21,70,154,Right,74,87,Aston Villa,74,...,3,High,Medium,1,67,67,72,74,69,70
4,212198,Bruno Fernandes,24,70,152,Right,85,88,Sporting CP,86,...,4,High,High,2,77,83,87,85,66,74

## value
We remove all special characters from value.

First, we investigate which extra characters exist so that we can decide how to treat them.

In [34]:
unique_chars = set()
for value in df['value']:
    for c in value:
        unique_chars.add(c)

In [35]:
unique_chars

{'.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K', 'M', '€'}

We can deal with the special characters as follows:
 - Drop the euro symbol
 - If there is `K` then multiply the value by 1 000
 - If there is 'M' then multiply the value by 1 000 000